config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  match '/' => redirect('graph'), via: :get
  resources :elos, :only => [:index]
  resources :games, :except => [:destroy, :show]
  resources :teams, :except => [:destroy, :show]
  resources :seasons, :except => [:destroy, :show]
  match 'seasons/refresh', :to => 'seasons#refresh', :via => [:get]
  match 'graph', :to => 'elos#graph',   :via => [:get]
  match 'lines', :to => 'elos#money_lines',   :via => [:get]
  match 'users', :to => 'users#create', :via => [:post]
  match 'login', :to => 'users#index',  :via => [:get]
  match 'logout',:to => 'users#logout', :via => [:get]
end

app/models/season.rb
require 'open-uri'

class Season < ActiveRecord::Base
  has_many :teams

  after_save :load_data
  validate :season_url

  SEASON_URL_IDENTIFIER = "Season"

  def load_data
    if (true == self.parse?)
      teams = {}

      pp = PointhogParser.new(PointhogParser.load_html(self.pointhog_url))

      pp.teams.each do |team_name|
        add_team(team_name)
      end

      pp.games.each do |game|
        home_team      = Team.lookup_home(game, self)
        away_team      = Team.lookup_away(game, self)
        ruby_game_date = game[PointhogParser::POINTHOG_DATE_COLUMN]

        if (false == home_team.home_games.exists?({:game_date => ruby_game_date}))
          g = Game.new
          g.home_team     = home_team
          g.away_team     = away_team
          g.home_score    = game[PointhogParser::HOME_SCORE_KEY]
          g.away_score    = game[PointhogParser::AWAY_SCORE_KEY]
          g.overtime      = game[PointhogParser::SHOOTOUT_KEY]
          g.game_date     = game[PointhogParser::POINTHOG_DATE_COLUMN]
          g.save!
        end
      end

      if (self.complete != pp.season_complete?)
        self.complete = pp.season_complete?
        self.save!

        if (true == self.complete?)
          teams_represented = Set.new

          self.games.order({:game_date => :desc}).each do |g|
            if ((false == teams_represented.include?(g.home_team.name)) || (false == teams_represented.include?(g.away_team.name)))
              if (true == teams_represented.empty?)
                g.championship = true
              else
                g.playoff = true
              end

              teams_represented << g.home_team.name
              teams_represented << g.away_team.name

              g.save!
            end
          end
        end
      end

      self.reload
    end
  end

  def short_name
    parts = name.split(" ")

    descriptor = parts.first.split("/").first
    year       = parts.last.split("/").first

    return "#{descriptor}#{year.last(2)}"
  end

  def start_date
    if (true == self.empty?)
      return Date.today
    else
      return self.games.select(:game_date).minimum(:game_date)
    end
  end

  def franchises
    return self.teams.select(:franchise).distinct.pluck(:franchise)
  end

  def empty?
    return self.games.empty?
  end

  def games
    return Game.where(:home_team_id => self.teams)
  end

  def parse?
    if (false == self.complete?)
      if (true == self.pointhog_url.is_a?(String))
        if ((Time.now.yesterday > self.updated_at) || (true == self.pointhog_url_changed?))
          return true
        end
      end
    end

    return false
  end

  def self.ordered_by_start_date(seasons)
    return seasons.sort_by { |season| season.start_date }
  end

  private
  def add_team(team_name)
    team = Team.new({:name => team_name})

    if (false == self.teams.exists?({:name => team.name}))
      self.teams << team
    end
  end

  def season_url
    if ((nil != self.pointhog_url) && (true == self.pointhog_url.include?(SEASON_URL_IDENTIFIER)))
      page = Nokogiri::HTML(open(self.pointhog_url))

      if ((nil == self.name) || (true == self.name.empty?))
        self.name = page.css('span[id*=ContentMain_ContentHeaderAndLogo1_ContentHeaderLabelTitle]').first.text.strip()
      end

      new_url = page.css("a[href*=#{PointhogParser::DIVISION_SCHEDULE_URL_IDENTIFIER}]").css("a[title*=B1]").first.attributes['href'].text

      if (nil == new_url)
        errors.add(:pointhog_url, "Couldn't parse season url correctly.")
        return false
      else
        Rails.logger.info("Detected season url changing url from '#{self.pointhog_url}' to '#{new_url}'.")
        self.pointhog_url = new_url
      end
    end

    return true
  end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  before_filter :elo_authorize, only: [:new, :edit, :update, :create, :refresh]
  before_action :set_season, only: [:edit, :update]

  # GET /seasons
  # GET /seasons.json
  def index
    @seasons = Season.all
  end

  # GET /seasons/new
  def new
    @season = Season.new
  end

  # GET /seasons/1/edit
  def edit
  end

  def refresh
    games = 0

    Season.where(:complete => false).each do |season|
      games -= season.games.size
      season.load_data
      games += season.games.size
    end

    respond_to do |format|
      format.html { redirect_to(seasons_url, {:notice => "'#{games.size}' new games loaded." }) }
    end
  end

  # POST /seasons
  # POST /seasons.json
  def create
    @season = Season.new(season_params)

    respond_to do |format|
      if @season.save
        format.html { redirect_to(seasons_url, {:notice => 'Season was successfully created.' }) }
        format.json { render :show, status: :created, location: @season }
      else
        format.html { render :new }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seasons/1
  # PATCH/PUT /seasons/1.json
  def update
    respond_to do |format|
      if @season.update(season_params)
        format.html { redirect_to(seasons_url, :notice => 'Season was successfully updated.') }
        format.json { render :show, status: :ok, location: @season }
      else
        format.html { render :edit }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_season
      @season = Season.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def season_params
      params.require(:season).permit(:name, :pointhog_url, :complete)
    end
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/views/seasons/_form.html.erb
<%= form_for(@season, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @season.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@season.errors.count, "error") %> prohibited this season from being saved:</h2>

      <ul>
      <% @season.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label(:name, :class => "col-sm-2 control-label") %>
    <div class="col-sm-8">
      <%= f.text_field(:name, :class => "form-control", :placeholder => :name) %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label(:pointhog_url, :class => "col-sm-2 control-label") %>
    <div class="col-sm-8">
      <%= f.text_field(:pointhog_url, :class => "form-control", :placeholder => :pointhog_url) %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-8">
      <div class="checkbox">
        <label>
        <%= f.check_box(:complete) %>Complete?
        </label>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit(:class => "btn btn-primary") %>
    </div>
  </div>
<% end %>

app/views/seasons/index.html.erb
<div class="navbar navbar-default" style="background-color:#FFFFFF;padding:5px 5px;">
  <p id="notice"><%= notice %></p>
  <p>
  <% if (true == logged_in?) %>
    <%= link_to new_season_path(), :class => "btn btn-default btn-sm" do %>
      <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New
    <% end %>
    <%= link_to 'seasons/refresh', :class => "btn btn-default btn-sm" do %>
      <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span> Reload
    <% end %>
  <% end %>
  </p>
  <table class="table table-striped">
    <tr>
      <th>name</th>
      <th>pointhog url</th>
      <th>games played</th>
      <th>start date</th>
      <th>complete?</th>
    </tr>
    <% Season.ordered_by_start_date(@seasons).reverse.each do |season| %>
      <tr>
        <td><%= link_to(season.name, edit_season_path(season)) %></td>
        <td><%= season.pointhog_url %></td>
        <td><%= season.games.size %></td>
        <td><%= season.start_date %></td>
        <td>
          <% if (true == season.complete?) %>
            <span class="glyphicon glyphicon-ok"></span>
          <% else %>
            <span class="glyphicon glyphicon-minus"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/seasons/new.html.erb
<%= render 'form' %>