config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  match '/' => redirect('graph'), via: :get
  resources :elos, :only => [:index]
  resources :games, :except => [:destroy, :show]
  resources :teams, :except => [:destroy, :show]
  resources :seasons, :except => [:destroy, :show]
  match 'seasons/refresh', :to => 'seasons#refresh', :via => [:get]
  match 'graph', :to => 'elos#graph',   :via => [:get]
  match 'lines', :to => 'elos#money_lines',   :via => [:get]
  match 'users', :to => 'users#create', :via => [:post]
  match 'login', :to => 'users#index',  :via => [:get]
  match 'logout',:to => 'users#logout', :via => [:get]
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :home_team, :class_name => 'Team', :foreign_key => "home_team_id"
  belongs_to :away_team, :class_name => 'Team', :foreign_key => "away_team_id"

  before_save :check_championship

  def to_s
    return "#{self.winner.abbreviated} d. #{self.loser.abbreviated} #{self.winner_score}-#{self.loser_score}"
  end
  alias :tooltip :to_s

  def annotation(franchise_name)
    if (true == self.championship?)
      if (franchise_name == self.winner.franchise)
        return "#{self.winner.franchise.abbreviated} Champions"
      elsif (franchise_name == self.loser.franchise)
        return "#{self.loser.franchise.abbreviated} Finals Loss"
      end
    end

    return nil
  end

  def winner_score
    return outcome[:winner][:score]
  end

  def winner
    return outcome[:winner][:team]
  end

  def loser_score
    return outcome[:loser][:score]
  end

  def loser
    return outcome[:loser][:team]
  end

  def season
    return self.home_team.season
  end

  private
  def outcome
    winner = {
      :team  => self.away_team,
      :score => self.away_score
    }
    loser  = {
      :team  => self.home_team,
      :score => self.home_score
    }

    if (self.home_score > self.away_score)
      tmp    = loser 
      loser  = winner
      winner = tmp
    end

    return {:winner => winner, :loser => loser}
  end

  def check_championship
    if (true == self.championship?)
      self.playoff = true
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_filter :elo_authorize, only: [:new, :edit, :update, :create]
  before_action :set_game, only: [:show, :edit, :update]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all.order(:game_date => :desc)
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to :back, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to :back, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:home_team_id, :home_score, :away_team_id, :away_score, :overtime, :game_date, :playoff, :championship)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :home_team_id %><br>
    <%= f.number_field :home_team_id %>
  </div>
  <div class="field">
    <%= f.label :home_score %><br>
    <%= f.number_field :home_score %>
  </div>
  <div class="field">
    <%= f.label :away_team_id %><br>
    <%= f.number_field :away_team_id %>
  </div>
  <div class="field">
    <%= f.label :away_score %><br>
    <%= f.number_field :away_score %>
  </div>
  <div class="field">
    <%= f.label :overtime %><br>
    <%= f.check_box :overtime %>
  </div>
  <div class="field">
    <%= f.label :playoff %><br>
    <%= f.check_box :playoff %>
  </div>
  <div class="field">
    <%= f.label :championship %><br>
    <%= f.check_box :championship %>
  </div>
  <div class="field">
    <%= f.label :game_date %><br>
    <%= f.date_select :game_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<div class="navbar navbar-default" style="background-color:#FFFFFF;padding:5px 5px;">
  <p id="notice"><%= notice %></p>
  <table class="table table-striped">
    <tr>
      <th>id</th>
      <th>game date</th>
      <th>home</th>
      <th>score</th>
      <th>away</th>
      <th>score</th>
      <th>overtime?</th>
      <th>playoff?</th>
      <th>championship?</th>
    </tr>
    <% @games.each do |game| %>
      <tr>
        <td><%= link_to(game.id, edit_game_path(game)) %></td>
        <td><%= game.game_date %></td>
        <td><%= game.home_team.name %></td>
        <td><%= game.home_score %></td>
        <td><%= game.away_team.name %></td>
        <td><%= game.away_score %></td>
        <td>
          <% if (true == game.overtime?) %>
            <span class="glyphicon glyphicon-ok"></span>
          <% else %>
            <span class="glyphicon glyphicon-minus"></span>
          <% end %>
        </td>
        <td>
          <% if (true == game.playoff?) %>
            <span class="glyphicon glyphicon-ok"></span>
          <% else %>
            <span class="glyphicon glyphicon-minus"></span>
          <% end %>
        </td>
        <td>
          <% if (true == game.championship?) %>
            <span class="glyphicon glyphicon-ok"></span>
          <% else %>
            <span class="glyphicon glyphicon-minus"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>